# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-12 04:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master', models.CharField(max_length=64, null=True, verbose_name='Master Name')),
                ('name', models.CharField(max_length=128, verbose_name='Scenario Name')),
                ('adult_only', models.BooleanField(choices=[(True, 'Adult Only'), (False, 'Free')], default=False, verbose_name='Adult Only')),
                ('gender_only', models.NullBooleanField(choices=[(None, 'Free'), (True, 'Male Only'), (False, 'Female Only')], default=None, verbose_name='Gender Only')),
                ('is_active', models.BooleanField(choices=[(False, 'Inactive'), (True, 'Active')], default=True, verbose_name='Is Active')),
                ('reg_date', models.DateTimeField(auto_now_add=True, verbose_name='Reg Date')),
                ('modify_date', models.DateTimeField(auto_now=True, verbose_name='Modify Date')),
            ],
            options={
                'verbose_name': 'Scenario',
                'verbose_name_plural': 'Scenarios',
            },
        ),
    ]
