# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-12 04:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=64)),
                ('scenario_name', models.CharField(max_length=128)),
                ('character_name', models.CharField(max_length=128)),
                ('player_reg_date', models.DateTimeField()),
                ('player_email', models.EmailField(max_length=64)),
            ],
        ),
    ]
