# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-12 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='player_phone_number',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
