# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-12 04:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Player Name')),
                ('nickname', models.CharField(max_length=64, verbose_name='Player Nickname')),
                ('phone_number', models.CharField(max_length=16, verbose_name='Phone Number')),
                ('gender', models.BooleanField(choices=[(True, 'Male'), (False, 'Female')], default=True, verbose_name='Gender')),
                ('is_adult', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True, verbose_name='Is Adult')),
                ('email', models.EmailField(max_length=64, verbose_name='Email')),
                ('reg_date', models.DateTimeField(auto_now_add=True, verbose_name='Reg Date')),
                ('modify_date', models.DateTimeField(auto_now=True, verbose_name='Modify Date')),
            ],
            options={
                'verbose_name': 'Player',
                'verbose_name_plural': 'Players',
            },
        ),
    ]
