# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 04:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='character',
            options={'ordering': ('scenario',), 'verbose_name': 'Character', 'verbose_name_plural': 'Characters'},
        ),
    ]
